database:
    username: "admin"
    password: "Love1998!!@@"
    sysdba: "n"
    host: (DESCRIPTION =
            (retry_count=20)
            (retry_delay=3)
            (address=(protocol=tcps)(port=1522)(host=adb.ap-seoul-1.oraclecloud.com))
            (connect_data=(service_name=ncyjsgjslztiofi_db202001291844_high.atp.oraclecloud.com))
            (security=(ssl_server_cert_dn="CN=adb.ap-seoul-1.oraclecloud.com,OU=Oracle ADB SEOUL,O=Oracle Corporation,L=Redwood City,ST=California,C=US"))
          )
